"""
CarSim Profile文件生成器 - 正确格式版本
"""
import shutil
import uuid
import numpy as np
from pathlib import Path
from datetime import datetime



def generate_pothole_profile(original_profile_path: str, 
                             output_dir: str,
                             depth_mm: float = 50.0,
                             position_m: float = 100.0,
                             width_m: float = 1.0) -> Path:
    """
    基于原始Profile生成带坑洼的新Profile文件
    
    Args:
        original_profile_path: 原始Profile文件路径
        output_dir: 输出目录
        depth_mm: 坑洼深度(mm)
        position_m: 坑洼中心位置(m)
        width_m: 坑洼宽度(m)
    
    Returns:
        生成的新Profile文件路径
    """
    
    # 生成新的UUID
    new_uuid = str(uuid.uuid4())
    output_path = Path(output_dir) / f"Profile_{new_uuid}.par"
    output_path.parent.mkdir(parents=True, exist_ok=True)
    
    # 读取原始Profile文件
    with open(original_profile_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 提取ISIDE 1的数据
    import re
    iside1_match = re.search(r'ISIDE 1\nZ_PROFILE_TABLE LINEAR_LOOP\n(.*?)\nENDTABLE', content, re.DOTALL)
    if not iside1_match:
        raise ValueError("未找到ISIDE 1数据")
    
    # 解析数据点
    lines = iside1_match.group(1).strip().split('\n')
    S = []
    Z = []
    for line in lines:
        line = line.strip()
        if line and not line.startswith('#'):
            parts = re.split(r'[,\s]+', line)
            parts = [p for p in parts if p]
            if len(parts) >= 2:
                S.append(float(parts[0]))
                Z.append(float(parts[1]))
    
    S = np.array(S)
    Z = np.array(Z)
    
    # 生成坑洼形状（余弦形状）
    half_width = width_m / 2
    dx = np.abs(S - position_m)
    mask = dx < half_width
    pothole = np.zeros_like(Z)
    pothole[mask] = -depth_mm * (1 + np.cos(np.pi * dx[mask] / half_width)) / 2
    
    # 叠加坑洼
    Z_new = Z + pothole
    
    # 生成新的ISIDE 1表格
    iside1_lines = []
    for s, z in zip(S, Z_new):
        iside1_lines.append(f"    {s:.3f}, {z:.2f}")
    iside1_table = '\n'.join(iside1_lines)
    
    # 提取ISIDE 2（保持与ISIDE 1相同，或从原文件提取）
    iside2_match = re.search(r'ISIDE 2\nZ_PROFILE_TABLE LINEAR_LOOP\n(.*?)\nENDTABLE', content, re.DOTALL)
    if iside2_match:
        # 保持原始ISIDE 2不变
        iside2_table = iside2_match.group(1).strip()
    else:
        iside2_table = iside1_table
    
    # 构建新的描述
    description = f"Rough Road_02_D{int(depth_mm)}mm_P{position_m}m"
    full_data_name = f"Surface: Roughness Profiles`{description}`Rough Road - Sample Data"
    
    # 生成新的Profile文件内容（正确格式，无缩进问题）
    new_content = f"""PARSFILE
#FullDataName {full_data_name}
#CheckBox0 0    

#RingCtrl0 LINEAR_LOOP
#DiagramOne0
ISIDE 1
Z_PROFILE_TABLE LINEAR_LOOP
{iside1_table}
ENDTABLE
#DiagramOne1
ISIDE 2
Z_PROFILE_TABLE LINEAR_LOOP
{iside2_table}
ENDTABLE
#RadioCtrl0 1    
#RadioCtrl1 1    

#EMBEDDED_NOTES
#Road roughness is elevation of the road that is added under the tires as the vehicle travels. It is not seen in the animator.
#
#Generated by Pothole Profile Generator
#Depth: {depth_mm}mm, Position: {position_m}m, Width: {width_m}m
#END_EMBEDDED_NOTES

LOG_ENTRY Used Dataset: Surface: Roughness Profiles; {{ {description} }} Rough Road - Sample Data
#Library : Surface: Roughness Profiles
#DataSet : {description}
#Category: Rough Road - Sample Data
#FileID  : Profile_{new_uuid}
#Modified: {datetime.now().strftime('%m-%d-%Y %H:%M:%S')}
#Product : CarSim 2024.1
#DataVer : 2024.1
#VehCode Roughness Profile

END
"""
    
    # 写入文件

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    print(f"✅ 生成Profile文件: {output_path}")
    print(f"   坑洼: 深度={depth_mm}mm, 位置={position_m}m, 宽度={width_m}m")
    
    return output_path


def update_run_all_with_new_profile(run_all_path: str, 
                                    new_profile_path: str,
                                    output_path: str = None) -> str:
    """
    更新Run_all.par中的Profile引用
    """
    # 读取原始Run_all.par
    with open(run_all_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # 构建新的配置段（使用正确的格式）
    with open(new_profile_path, 'r', encoding='utf-8') as f:
        profile_content = f.read()
    
    # 提取FullDataName
    import re
    full_data_name = re.search(r'#FullDataName (.+?)\n', profile_content).group(1)
    
    # 提取ISIDE 1
    iside1_match = re.search(r'ISIDE 1\nZ_PROFILE_TABLE LINEAR_LOOP\n(.*?)\nENDTABLE', profile_content, re.DOTALL)
    iside1_table = iside1_match.group(1).strip()
    
    # 提取ISIDE 2
    iside2_match = re.search(r'ISIDE 2\nZ_PROFILE_TABLE LINEAR_LOOP\n(.*?)\nENDTABLE', profile_content, re.DOTALL)
    iside2_table = iside2_match.group(1).strip() if iside2_match else iside1_table
    
    # 提取LOG_ENTRY
    log_entry = re.search(r'LOG_ENTRY (.+?)\n', profile_content).group(1)
    
    profile_name = Path(new_profile_path).name
    
    # 构建新配置段（保持与原始Run_all.par相同的格式）
    new_section = f"""ENTER_PARSFILE Roads\\Profiles\\{profile_name}
#FullDataName {full_data_name}
ISIDE 1
Z_PROFILE_TABLE LINEAR_LOOP
{iside1_table}
ENDTABLE
ISIDE 2
Z_PROFILE_TABLE LINEAR_LOOP
{iside2_table}
ENDTABLE
LOG_ENTRY {log_entry}
EXIT_PARSFILE Roads\\Profiles\\{profile_name}\n"""
    
    # 查找并替换（使用字符串查找，不用正则）
    start_marker = "ENTER_PARSFILE Roads\\Profiles\\"
    end_marker = "EXIT_PARSFILE Roads\\Profiles\\"
    
    start_idx = content.find(start_marker)
    if start_idx == -1:
        # 尝试正斜杠
        start_marker = "ENTER_PARSFILE Roads/Profiles/"
        end_marker = "EXIT_PARSFILE Roads/Profiles/"
        start_idx = content.find(start_marker)
    
    if start_idx != -1:
        end_idx = content.find(end_marker, start_idx)
        if end_idx != -1:
            # 找到EXIT行的结束
            end_line_idx = content.find('\n', end_idx)
            if end_line_idx != -1:
                end_idx = end_line_idx + 1
            
            # 替换
            new_content = content[:start_idx] + new_section + content[end_idx:]
            
            # 保存
            if output_path is None:
                output_path = run_all_path
            else:
                output_path = Path(output_path)
                output_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(output_path, 'w', encoding='utf-8') as f:
                f.write(new_content)
            
            print(f"✅ 已更新Run_all.par: {output_path}")
            return str(output_path)
    
    print("❌ 未找到Profile配置段")
    return None


# ==================== 使用示例 ====================

if __name__ == "__main__":
    # 配置路径
    ORIGINAL_PROFILE = r"./Results/Run_3563bff4-4dd7-43e7-a5f6-58f9da20a0a7/Profile_3bff0c88-84c1-408a-843d-956a1e2abe43.par"
    RUN_ALL_PATH = r"./Results/Run_3563bff4-4dd7-43e7-a5f6-58f9da20a0a7/Run_all.par"
    OUTPUT_DIR = r"./Results/Run_3563bff4-4dd7-43e7-a5f6-58f9da20a0a7/profiles"
    
    # 生成带坑洼的Profile文件
    new_profile = generate_pothole_profile(
        original_profile_path=ORIGINAL_PROFILE,
        output_dir=OUTPUT_DIR,
        depth_mm=5000,      # 5m深的坑
        position_m=100,   # 100米处
        width_m=5.0       # 5米宽
    )
    
    # 更新Run_all.par
    update_run_all_with_new_profile(
        run_all_path=RUN_ALL_PATH,
        new_profile_path=new_profile,
        output_path=OUTPUT_DIR + "/Run_all_updated.par"
    )